/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author blazquez.asier
 */
public class HandienaGUI extends javax.swing.JFrame {

    /**
     * Creates new form HandienaGUI
     */
    static Zatikia[] zatikiak = new Zatikia[3];

    public HandienaGUI() {
        initComponents();
        buttonGroup1.add(rdbutton1);
        buttonGroup1.add(rdbutton2);
        buttonGroup1.add(rdbutton3);
        sortu();
    }

    private void sortu() {
        Zatikia.zatikiakRandom(zatikiak);

        zenbBat.setText(String.valueOf(zatikiak[0].getZenbakitzailea()));
        zenbBi.setText(String.valueOf(zatikiak[1].getZenbakitzailea()));
        zenbHiru.setText(String.valueOf(zatikiak[2].getZenbakitzailea()));
        izenBat.setText(String.valueOf(zatikiak[0].getIzendatzailea()));
        izenBi.setText(String.valueOf(zatikiak[1].getIzendatzailea()));
        izenHiru.setText(String.valueOf(zatikiak[2].getIzendatzailea()));
    }

    private double handiena() {
        double max = 0;
        for (int i = 0; i < zatikiak.length; i++) {
            if (zatikiak[i].hamartarBaliokidea() >= max) {
                max = zatikiak[i].hamartarBaliokidea();
            }
        }
        return max;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titulo = new java.awt.Label();
        izenBat = new javax.swing.JLabel();
        zenbBat = new javax.swing.JLabel();
        zenbBi = new javax.swing.JLabel();
        izenBi = new javax.swing.JLabel();
        zenbHiru = new javax.swing.JLabel();
        izenHiru = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saiatu = new javax.swing.JButton();
        comprobar = new javax.swing.JButton();
        labelOkerra = new javax.swing.JLabel();
        labelzuzena = new javax.swing.JLabel();
        rdbutton1 = new javax.swing.JRadioButton();
        rdbutton2 = new javax.swing.JRadioButton();
        rdbutton3 = new javax.swing.JRadioButton();
        oklabel = new javax.swing.JLabel();
        sadlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 51, 255));
        titulo.setText("Handiena Bilatu");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, 420, 80));
        titulo.getAccessibleContext().setAccessibleName("k");

        izenBat.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(izenBat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 50, 70));

        zenbBat.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(zenbBat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 50, 70));

        zenbBi.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(zenbBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 50, 70));

        izenBi.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(izenBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 50, 70));

        zenbHiru.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(zenbHiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 50, 70));

        izenHiru.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(izenHiru, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 50, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 85)); // NOI18N
        jLabel1.setText("_");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 70, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 85)); // NOI18N
        jLabel2.setText("_");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 133, 70, 110));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 85)); // NOI18N
        jLabel3.setText("_");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 70, 110));

        saiatu.setText("Saiatu Berriro");
        saiatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saiatuActionPerformed(evt);
            }
        });
        getContentPane().add(saiatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 150, 50));

        comprobar.setText("Frogatu Emaitza");
        comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarActionPerformed(evt);
            }
        });
        getContentPane().add(comprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 150, 50));

        labelOkerra.setVisible(false);
        labelOkerra.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelOkerra.setForeground(new java.awt.Color(255, 51, 51));
        labelOkerra.setText("OKERRA!!");
        getContentPane().add(labelOkerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 350, 70));

        labelzuzena.setVisible(false);
        labelzuzena.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelzuzena.setForeground(new java.awt.Color(51, 204, 0));
        labelzuzena.setText("ZUZENA!!!!!");
        getContentPane().add(labelzuzena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 350, 70));

        rdbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));
        getContentPane().add(rdbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
        getContentPane().add(rdbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        oklabel.setVisible(false);
        oklabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.gif"))); // NOI18N
        getContentPane().add(oklabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 320, 250));

        sadlabel.setVisible(false);
        sadlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/triste.png"))); // NOI18N
        getContentPane().add(sadlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 350, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saiatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saiatuActionPerformed
        buttonGroup1.clearSelection();
        labelOkerra.setVisible(false);
        sadlabel.setVisible(false);
        oklabel.setVisible(false);
        labelzuzena.setVisible(false);
        rdbutton1.setSelected(false);
        rdbutton2.setSelected(false);
        rdbutton3.setSelected(false);

        sortu();


    }//GEN-LAST:event_saiatuActionPerformed

    private void comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarActionPerformed
        // TODO add your handling code here:
         labelOkerra.setVisible(false);
         sadlabel.setVisible(false);
        labelzuzena.setVisible(false);
        oklabel.setVisible(false);
        rdbutton1.setSelected(false);
        rdbutton2.setSelected(false);
        rdbutton3.setSelected(false);
        if (rdbutton1.isSelected()) {

            if (handiena() == zatikiak[0].hamartarBaliokidea()) {

                labelzuzena.setVisible(true);
                oklabel.setVisible(true);

            } else {
                labelOkerra.setVisible(true);
                sadlabel.setVisible(true);
            }

        }
        if (rdbutton2.isSelected()) {

            if (handiena() == zatikiak[1].hamartarBaliokidea()) {

                labelzuzena.setVisible(true);
                oklabel.setVisible(true);

            } else {
                labelOkerra.setVisible(true);
                sadlabel.setVisible(true);
            }

        }
        if (rdbutton3.isSelected()) {

            if (handiena() == zatikiak[2].hamartarBaliokidea()) {

                labelzuzena.setVisible(true);
                oklabel.setVisible(true);

            } else {
                labelOkerra.setVisible(true);
                sadlabel.setVisible(true);
            }

        }

    }//GEN-LAST:event_comprobarActionPerformed

    private void rdbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HandienaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HandienaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HandienaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HandienaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HandienaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton comprobar;
    private javax.swing.JLabel izenBat;
    private javax.swing.JLabel izenBi;
    private javax.swing.JLabel izenHiru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelOkerra;
    private javax.swing.JLabel labelzuzena;
    private javax.swing.JLabel oklabel;
    private javax.swing.JRadioButton rdbutton1;
    private javax.swing.JRadioButton rdbutton2;
    private javax.swing.JRadioButton rdbutton3;
    private javax.swing.JLabel sadlabel;
    private javax.swing.JButton saiatu;
    private java.awt.Label titulo;
    private javax.swing.JLabel zenbBat;
    private javax.swing.JLabel zenbBi;
    private javax.swing.JLabel zenbHiru;
    // End of variables declaration//GEN-END:variables
}
