
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author blazquez.asier
 */
public class Menua extends javax.swing.JFrame {

    /**
     * Creates new form Menua
     */
    public Menua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new java.awt.Label();
        sortuButton = new javax.swing.JButton();
        sortuButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 51, 255));
        titulo.setText("ZATIKIAK");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 300, 90));

        sortuButton.setText("Zatiki Handiena Bilatu");
        sortuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 50));

        sortuButton1.setText("Zatiki Asko Sortu");
        sortuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortuButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(sortuButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nums.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 510, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortuButtonActionPerformed
        // TODO add your handling code here:
        JFrame entrar = new HandienaGUI();
	entrar.setVisible(true);
        //this.dispose(); 
    }//GEN-LAST:event_sortuButtonActionPerformed

    private void sortuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortuButton1ActionPerformed
        // TODO add your handling code here:
           JFrame entrar = new ZatikiakSortuGUI();
            entrar.setVisible(true);
            //this.dispose(); 
    }//GEN-LAST:event_sortuButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sortuButton;
    private javax.swing.JButton sortuButton1;
    private java.awt.Label titulo;
    // End of variables declaration//GEN-END:variables
}
