
import java.util.Arrays;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author blazquez.asier
 */
public class ZatikiakSortuGUI extends javax.swing.JFrame {

    private static Zatikia[] zatikiak;

    /**
     * Creates new form ZatikiakSortuGUI
     */
    public ZatikiakSortuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelzatikiak = new javax.swing.JLabel();
        titulo = new java.awt.Label();
        zenbatBox = new javax.swing.JComboBox<>();
        sortuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelsortu = new javax.swing.JLabel();
        buttonSimplifikatu = new javax.swing.JButton();
        Ordenatu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelzatikiak.setVisible(false);
        labelzatikiak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelzatikiak.setForeground(new java.awt.Color(255, 51, 153));
        getContentPane().add(labelzatikiak, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 760, 40));

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 51, 255));
        titulo.setText("Sortu");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 300, 90));

        zenbatBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        zenbatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zenbatBoxActionPerformed(evt);
            }
        });
        getContentPane().add(zenbatBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 60, 30));

        sortuButton.setLabel("Sortu");
        sortuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sortuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 160, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Zenbat Zatiki sortu nahi dituzu?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 260, 40));

        labelsortu.setVisible(false);
        labelsortu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelsortu.setText("Sortutako Zatikiak");
        getContentPane().add(labelsortu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 40));

        buttonSimplifikatu.setVisible(false);
        buttonSimplifikatu.setText("Simplifikatu");
        buttonSimplifikatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimplifikatuActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSimplifikatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 160, 60));

        Ordenatu.setVisible(false);
        Ordenatu.setText("Ordenatu");
        Ordenatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenatuActionPerformed(evt);
            }
        });
        getContentPane().add(Ordenatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 160, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zenbatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zenbatBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zenbatBoxActionPerformed

    private void sortuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortuButtonActionPerformed
        // TODO add your handling code here:
        String zenbat = (String) zenbatBox.getSelectedItem();

        int input = showConfirmDialog(null, zenbat + " Zatiki sortu nahi dituzu?");

        if (input == 0) {
            zatikiak = new Zatikia[Integer.parseInt(zenbat)];
            Zatikia.zatikiakRandom(zatikiak);

            input = showConfirmDialog(null, "Zatikiak simplifikatu nahi dituzu?");
            if (input == 0) {
                for (int i = 0; i < zatikiak.length; i++) {
                    zatikiak[i].sinplifikatu();
                }
            } else {
                buttonSimplifikatu.setVisible(true);
            }
            labelzatikiak.setText(Arrays.toString(zatikiak));
            labelsortu.setVisible(true);
            labelzatikiak.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(null, "Ez dituzu zatikirik sortu 😒😒", "Error", JOptionPane.WARNING_MESSAGE);
        }

        Ordenatu.setVisible(true);
    }//GEN-LAST:event_sortuButtonActionPerformed

    private void buttonSimplifikatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimplifikatuActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < zatikiak.length; i++) {
            zatikiak[i].sinplifikatu();
        }
                showMessageDialog(null, "Zatikiak simplifikatu dira ", "Informazioa", JOptionPane.INFORMATION_MESSAGE);


        labelzatikiak.setText(Arrays.toString(zatikiak));
        buttonSimplifikatu.setVisible(false);


    }//GEN-LAST:event_buttonSimplifikatuActionPerformed

    private void OrdenatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenatuActionPerformed
        // TODO add your handling code here:
        zatikiak[0].zatikiakOrdenatu(zatikiak);
        showMessageDialog(null, "Zatikiak ordenatu dira txikienetik handienera ", "Informazioa", JOptionPane.INFORMATION_MESSAGE);
        labelzatikiak.setText(Arrays.toString(zatikiak));
        Ordenatu.setVisible(false);

    }//GEN-LAST:event_OrdenatuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZatikiakSortuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZatikiakSortuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZatikiakSortuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZatikiakSortuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZatikiakSortuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ordenatu;
    private javax.swing.JButton buttonSimplifikatu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelsortu;
    private javax.swing.JLabel labelzatikiak;
    private javax.swing.JButton sortuButton;
    private java.awt.Label titulo;
    private javax.swing.JComboBox<String> zenbatBox;
    // End of variables declaration//GEN-END:variables
}
