/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import model.Langilea;
import model.Zatikia;

/**
 *
 * @author blazquez.asier
 */
public class LangileenDatuakGUI extends javax.swing.JFrame {

    /**
     * Creates new form LangileenDatuakGUI
     */
    public static Langilea[] langileak = Langilea.nireHamarLagunLangile();
    static  int i = 0;

    public LangileenDatuakGUI() {
        initComponents();
        sortu();
    }

    public void sortu() {

        izenaField.setText(langileak[i].getIzena());
        abizenaField.setText(langileak[i].getAbizena());
        soldataField.setText(String.valueOf(langileak[i].getSoldata()));
        fieldLanaldia.setText(String.valueOf(langileak[i].getLanaldia().getZenbakitzailea()) + "/" + String.valueOf(langileak[i].getLanaldia().getIzendatzailea()));
        orduakfield.setText(String.valueOf((langileak[i].getLanaldia().hamartarBaliokidea() * 35)));
        idLangile.setText(String.valueOf(langileak[i].getId()));
        izenOsoaLabel.setText((String.valueOf(langileak[i].getIzenOsoa())));
        if (i <= 0) {
            atrasButton.setEnabled(false);
        } else {
            atrasButton.setEnabled(true);
        }
        if (i >= langileak.length - 1) {
            nextButton.setEnabled(false);
        } else {
            nextButton.setEnabled(true);
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orduakfield = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        abizenaField = new javax.swing.JTextField();
        izenaField = new javax.swing.JTextField();
        soldataField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldLanaldia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        amaituButton = new javax.swing.JButton();
        atrasButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        soldataIgo = new javax.swing.JButton();
        soldataText = new javax.swing.JSpinner();
        idLangile = new javax.swing.JLabel();
        izenOsoaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Langileak");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 210, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Izena");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 50, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Abizena");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 50, 30));

        orduakfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(orduakfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 80, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, 330, 300));

        abizenaField.setEditable(false);
        abizenaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abizenaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(abizenaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 210, 30));

        izenaField.setEditable(false);
        izenaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izenaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(izenaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 210, 30));

        soldataField.setEditable(false);
        soldataField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldataFieldActionPerformed(evt);
            }
        });
        getContentPane().add(soldataField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 110, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Soldata");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 50, 30));

        fieldLanaldia.setEditable(false);
        getContentPane().add(fieldLanaldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 90, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Lanaldia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 50, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Astean egiten dituen orduak");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 180, 30));

        editarButton.setText("Datuak Aldatu");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 113, 130, 40));

        amaituButton.setVisible(false);
        amaituButton.setText("Amaitu edizioa");
        amaituButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amaituButtonActionPerformed(evt);
            }
        });
        getContentPane().add(amaituButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 130, 40));

        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atas.png"))); // NOI18N
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(atrasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 620, -1, -1));

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aurrera.png"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, -1, -1));

        soldataIgo.setVisible(false);
        soldataIgo.setText("Soldata Igo %");
        soldataIgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldataIgoActionPerformed(evt);
            }
        });
        getContentPane().add(soldataIgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 110, 40));

        soldataText.setVisible(false);
        getContentPane().add(soldataText, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 60, 40));

        idLangile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(idLangile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 20, 40));

        izenOsoaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(izenOsoaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 240, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abizenaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abizenaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abizenaFieldActionPerformed

    private void izenaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izenaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izenaFieldActionPerformed

    private void soldataFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldataFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soldataFieldActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
        //   izenaField.setEditable(true);
        //  abizenaField.setEditable(true);

        soldataField.setEditable(true);
        fieldLanaldia.setEditable(true);
        showMessageDialog(null, "Orain datuak aldatu ahal dituzu", "Informazioa", JOptionPane.INFORMATION_MESSAGE);
        editarButton.setVisible(false);
        amaituButton.setVisible(true);
        soldataIgo.setVisible(true);
        soldataText.setVisible(true);
        nextButton.setVisible(false);
        atrasButton.setVisible(false);


    }//GEN-LAST:event_editarButtonActionPerformed

    private void amaituButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amaituButtonActionPerformed
        // TODO add your handling code here:
        int confirm = showConfirmDialog(null, "Datuak Gorde nahi dituzu?");

        if (confirm == 0) {

            try {
                langileak[i].setSoldata(Double.parseDouble(soldataField.getText()));
                langileak[i].setLanaldia(new Zatikia(fieldLanaldia.getText()));
            } catch (Exception ex) {
                showMessageDialog(null, "Datu okerrak sartu dituzu", "Errorea", JOptionPane.ERROR_MESSAGE);

            }
        }

        editarButton.setVisible(true);
        amaituButton.setVisible(false);
        soldataField.setEditable(false);
        fieldLanaldia.setEditable(false);
        soldataIgo.setVisible(false);
        soldataText.setVisible(false);
        nextButton.setVisible(true);
        atrasButton.setVisible(true);

        sortu();

    }//GEN-LAST:event_amaituButtonActionPerformed

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed

        i = i - 1;

        sortu();


    }//GEN-LAST:event_atrasButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        i = i + 1;
        sortu();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void soldataIgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldataIgoActionPerformed
        // TODO add your handling code here:

        int confirm = showConfirmDialog(null, "Soldata " + soldataText.getValue() + "% igo nahi duzu ?");

        if (confirm == 0) {
            langileak[i].soldataIgo((int) soldataText.getValue());
            sortu();
        }

    }//GEN-LAST:event_soldataIgoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LangileenDatuakGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LangileenDatuakGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LangileenDatuakGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LangileenDatuakGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LangileenDatuakGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abizenaField;
    private javax.swing.JButton amaituButton;
    private javax.swing.JButton atrasButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JTextField fieldLanaldia;
    private javax.swing.JLabel idLangile;
    private javax.swing.JLabel izenOsoaLabel;
    private javax.swing.JTextField izenaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel orduakfield;
    private javax.swing.JTextField soldataField;
    private javax.swing.JButton soldataIgo;
    private javax.swing.JSpinner soldataText;
    // End of variables declaration//GEN-END:variables
}
