/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author blazg
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        datuakButton = new javax.swing.JButton();
        bilatuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Langileak Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 310, 50));

        datuakButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        datuakButton.setText("Langileen datuak ");
        datuakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datuakButtonActionPerformed(evt);
            }
        });
        getContentPane().add(datuakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 190, 80));

        bilatuButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bilatuButton.setText("Langileak Bilatu");
        bilatuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilatuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bilatuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datuakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datuakButtonActionPerformed
        // TODO add your handling code here:
        JFrame entrar = new LangileenDatuakGUI();
        entrar.setVisible(true);
    }//GEN-LAST:event_datuakButtonActionPerformed

    private void bilatuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilatuButtonActionPerformed
        // TODO add your handling code here:
        JFrame entrar = new BilatuGUI();

        entrar.setVisible(true);
    }//GEN-LAST:event_bilatuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bilatuButton;
    private javax.swing.JButton datuakButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
