package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author blazquez.asier
 */
public class AsmatuGUI extends javax.swing.JFrame {

    private final int puntuazioa = 0;
    private int aleatorio = -1;
    int tiempo = 25; //tiempo

    /**
     * Creates new form Asmatu
     */
    // private ImageIcon icon;
    public AsmatuGUI() {
        initComponents();
        Collections.shuffle(MainGUI.marrazkiak);

        aldatuArgazkia();

    }

    public void aldatuArgazkia() {
        aleatorio++;
        // aleatorio = (int) (Math.random() * MainGUI.marrazkiak.size());           
        if (aleatorio == MainGUI.marrazkiak.size() - 1) {
            JOptionPane.showMessageDialog(null, "Partida amaituta", "Informazioa", JOptionPane.INFORMATION_MESSAGE);
            timeLabel.setVisible(false);
            cambiar.setVisible(false);
        } else {

            argazkia.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainGUI.marrazkiak.get(aleatorio).getImagen())));
            labelzuzena.setVisible(false);
            labelOkerra.setVisible(false);
            palabraIntro.setText("");
            pistaLabel.setVisible(false);
            pistaButton.setVisible(true);
            timer.start();
            tiempo = 25;   //cambiar este valor para cambiar el tiempo
            timeLabel.setText(tiempo + "");

        }

    }

    public void frogratuHitza() {
        if (palabraIntro.getText().toLowerCase().equals(MainGUI.marrazkiak.get(aleatorio).getIzena())) {
            labelzuzena.setVisible(true);
            labelOkerra.setVisible(false);
            timer.stop();

        } else {
            palabraIntro.setText("");
            labelzuzena.setVisible(false);
            labelOkerra.setVisible(true);

        }

    }

    //..... TEMPORIZADOR....
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {

            tiempo--;
            timeLabel.setText(tiempo + "");
            if(tiempo == 10){
            pistaLetra();
            }
            if (tiempo == 0) {
                timer.stop();
                frogratuHitza();
            }

        }
    });

    public void pistaBatEman() {

        pistaButton.setVisible(false);
        pistaLabel.setVisible(true);
        String guion = "";

        for (int i = 1; i <= MainGUI.marrazkiak.get(aleatorio).getLetraZenbakia(); i++) {

            guion = guion + " _";

        }
        pistaLabel.setText(guion);

    }

    public void pistaLetra() {
        pistaButton.setVisible(false);
        pistaLabel.setVisible(true);

        String izena = MainGUI.marrazkiak.get(aleatorio).getIzena();
        int al = (int) (Math.random() * izena.length());
        String guion = "";

        for (int i = 1; i <= MainGUI.marrazkiak.get(aleatorio).getLetraZenbakia(); i++) {
            if (i == al+1) {
                guion = guion + " " + izena.charAt(al);
            } else {
                guion = guion + " _";

            }

        }
        pistaLabel.setText(guion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new java.awt.Label();
        palabraIntro = new javax.swing.JTextField();
        frogratu = new javax.swing.JButton();
        argazkia = new javax.swing.JLabel();
        cambiar = new javax.swing.JButton();
        labelOkerra = new javax.swing.JLabel();
        labelzuzena = new javax.swing.JLabel();
        pistaButton = new javax.swing.JButton();
        timeLabel = new java.awt.Label();
        pistaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(1400, 1100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 255));
        titulo.setText("ASMATU ");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 420, 80));
        titulo.getAccessibleContext().setAccessibleName("");

        palabraIntro.setBackground(new java.awt.Color(240, 240, 240));
        palabraIntro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        palabraIntro.setToolTipText("");
        palabraIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraIntroActionPerformed(evt);
            }
        });
        getContentPane().add(palabraIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 340, 60));

        frogratu.setText("Frogatu");
        frogratu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frogratuActionPerformed(evt);
            }
        });
        getContentPane().add(frogratu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 390, 110, 40));

        argazkia.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(argazkia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 700, 700));

        cambiar.setText("Beste Bat");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });
        getContentPane().add(cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 720, 150, 40));

        labelOkerra.setVisible(false);
        labelOkerra.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelOkerra.setForeground(new java.awt.Color(255, 51, 51));
        labelOkerra.setText("OKERRA!!");
        getContentPane().add(labelOkerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, 250, 70));

        labelzuzena.setVisible(false);
        labelzuzena.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelzuzena.setForeground(new java.awt.Color(51, 204, 0));
        labelzuzena.setText("ZUZENA!!!!!");
        getContentPane().add(labelzuzena, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, 310, 70));

        pistaButton.setText("Pista bat eman");
        pistaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pistaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 170, 40));

        timeLabel.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        getContentPane().add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, 180, 120));

        pistaLabel.setVisible(false);
        pistaLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pistaLabel.setText("_ _ _ _ _ _ _ _ _ _ _");
        getContentPane().add(pistaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 350, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void palabraIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraIntroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabraIntroActionPerformed

    private void frogratuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frogratuActionPerformed
        // TODO add your handling code here:
        System.out.println(MainGUI.marrazkiak.get(aleatorio).getIzena());
        frogratuHitza();

    }//GEN-LAST:event_frogratuActionPerformed

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        // TODO add your handling code here:
        aldatuArgazkia();

        System.out.println(MainGUI.marrazkiak);

    }//GEN-LAST:event_cambiarActionPerformed

    private void pistaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistaButtonActionPerformed
        // TODO add your handling code here:

        pistaBatEman();
    }//GEN-LAST:event_pistaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsmatuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsmatuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsmatuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsmatuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsmatuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel argazkia;
    private javax.swing.JButton cambiar;
    private javax.swing.JButton frogratu;
    private javax.swing.JLabel labelOkerra;
    private javax.swing.JLabel labelzuzena;
    private javax.swing.JTextField palabraIntro;
    private javax.swing.JButton pistaButton;
    private javax.swing.JLabel pistaLabel;
    private java.awt.Label timeLabel;
    private java.awt.Label titulo;
    // End of variables declaration//GEN-END:variables
}
