
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author blazquez.asier
 */
public class Asmatu extends javax.swing.JFrame {

    /**
     * Creates new form Asmatu
     */
    public Asmatu() {
        initComponents();
        sortu();
    }
    Marrazkia m1 = new Marrazkia(1, "CASA");
    
        private static ArrayList<Marrazkia> marrazkiak;
        



    public void sortu() {
        int id =0;
        marrazkiak = new ArrayList<>();
        marrazkiak.add(new Marrazkia(id++, "CASA"));
        marrazkiak.add(new Marrazkia(id++, "COCHE"));
        marrazkiak.add(new Marrazkia(id++, "EDIFICIO"));
        marrazkiak.add(new Marrazkia(id++, "AVION"));
        marrazkiak.add(new Marrazkia(id++, "ORDENADOR"));
        marrazkiak.add(new Marrazkia(id++, "MESA"));
        marrazkiak.add(new Marrazkia(id++, "TECLADO"));
        marrazkiak.add(new Marrazkia(id++, "PANTALLA"));
   int aleatorio = (int) (Math.random()*marrazkiak.size());

        argazkia.setText(marrazkiak.get(aleatorio).getIzena());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new java.awt.Label();
        palabraIntro = new javax.swing.JTextField();
        frogratu = new javax.swing.JButton();
        argazkia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 255));
        titulo.setText("ASMATU ");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, 420, 80));
        titulo.getAccessibleContext().setAccessibleName("");

        palabraIntro.setToolTipText("");
        palabraIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraIntroActionPerformed(evt);
            }
        });
        getContentPane().add(palabraIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 180, 40));

        frogratu.setText("Frogatu");
        frogratu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frogratuActionPerformed(evt);
            }
        });
        getContentPane().add(frogratu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 110, 50));
        getContentPane().add(argazkia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 340, 240));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void palabraIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraIntroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabraIntroActionPerformed

    private void frogratuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frogratuActionPerformed
        // TODO add your handling code here:
        
        
     
        if (palabraIntro.getText().toUpperCase().equals(argazkia.getText())) {
            showMessageDialog(null, "LAS PALABRAS COINCIDEN", "Informazioa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            showMessageDialog(null, "LAS PLABRAS NO COINCIDEN", "Informazioa", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_frogratuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        sortu();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asmatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asmatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asmatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asmatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asmatu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel argazkia;
    private javax.swing.JButton frogratu;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField palabraIntro;
    private java.awt.Label titulo;
    // End of variables declaration//GEN-END:variables
}
