
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Frame;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showConfirmDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author blazg
 */
public class MarraztuGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUIPRUEBA
     */
    public MarraztuGUI() {
        initComponents();
        verLienzo();
    }

    Dibujar lienzo;

    public void verLienzo() {
        // create main frame

        JFrame frame = new JFrame("Lienzo");
        Container content = frame.getContentPane();
        content.setLayout(new BorderLayout());
        lienzo = new Dibujar();
        content.add(lienzo, BorderLayout.CENTER);
        frame.setSize(600, 600);
        // can close frame
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);

        // Now you can try our Swing Paint !!! Enjoy :D
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        GordeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Herramientas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Herramientas");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, 60));
        label1.getAccessibleContext().setAccessibleName("Herramientas");

        GordeButton.setText("Gorde");
        GordeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GordeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GordeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GordeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GordeButtonActionPerformed
        // TODO add your handling code here:
        
        int input = showConfirmDialog(null, " Marrazkia Gorde nahi duzu?");
        
        if(input==0){
          Marrazkia m = new Marrazkia(1, "dibu", "dibu");
          lienzo.savee(m);
          Asmatu.ArrayeanGehitu(m);
          
        
        
        }

    }//GEN-LAST:event_GordeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarraztuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarraztuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarraztuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarraztuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarraztuGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GordeButton;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
